### ISSUE TITLE
jQuery cannot be loaded due to HTTP-HTTPS mixed content

### ISSUE THREAD

**Issue by gheja** [davidbkemp/QuantumComputingArticle#4]
Chrome 57 reports a mixed content error that causes jQuery load to fail.

Error:
`Mixed Content: The page at 'https://davidbkemp.github.io/QuantumComputingArticle/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by davidbkemp** [comment]
Thanks for reporting this.

Hopefully it works now.

My solution is not elegant, but I haven't got time or head space to fix it properly.  I wrote this article several years ago and it's only now that it has been posted to hacker-news that all of sudden people are finding it!

**Comment by gheja** [comment]
Not elegant but effective :)

Oh, and thanks for the article and the demos!

**Comment by gheja** [comment]
Just remembered you could use `//` instead of `http://` or `https://` and it will choose the correct one (it's called [protocol-relative URL](https://www.paulirish.com/2010/the-protocol-relative-url/) and it will always match to the protocol the browser used to open the page).

Only drawback is that if opened locally then `file://` will be chosen which would be invalid.

Personally, I don't like to depend on external resources so would stay with your current solution but there's this option, too.

**Comment by heyyou89** [comment]
Quick fix (not recommended) to replace http:// with https:// in  src="http://ajax.whatever .
