### ISSUE TITLE
Clarify how oracle function is applied in "Quatum Search over 2 Qubits" section

### ISSUE THREAD

**Issue by vovcacik** [davidbkemp/QuantumComputingArticle#5]
Hi, great article! I had a bit of trouble to understand the big picture in *Quatum Search over 2 Qubits* section.

First time I saw the example I failed to see any benefit --- after all in the first step I *mark the correct answer* using the f00, f01, f10 or f11 buttons and then all the algorithm does is making the state with inverted phase to be 100% likely.

Maybe it could be improved by
- stressing it is about inverting the function, in your example it was oracle function
- the function is called once, but changes all the four states (am I right?); this is the mindblowing part
- could you provide example of concrete function that works on two qubits

**Comment by davidbkemp** [comment]
Thanks for the feedback Vlastimil.  I agree that the section on 2-qubit search needed improvements.  I have just published my attempt at improving it.

I suspect most of the people who will ever read my article will have already read it, but it seems to be still attracting some traffic, and so I figured I should attempt to clarify it.

Cheers,
David

**Comment by vovcacik** [comment]
I read the commit and then the affected sections and I like the changes. I know this is probably very basic stuff, but with the changes I (as a layman) feel like I keep up with the text better.

Thanks!
